# Generated by Django 5.2.4 on 2025-08-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_post_likes_alter_post_user_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='No Title', max_length=255),
            preserve_default=False,
        ),
    ]
